services:
  webserv:
    build: ./nginx
    container_name: ygaiffie-webserv
    ports:
      - "80:80"
      - "443:443"
    #volumes:
    #  - /opt/www:/var/www
    networks:
      - inception

  mysql:
    build: ./mariadb
    container_name: ygaiffie-db
    volumes:
      - /opt/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception
    
  redis:
    build: ./redis
    container_name: ygaiffie-redis
    ports:
      - "6379:6379"
    networks:
      - inception

  wordpress:
    build: ./wp_php
    container_name: ygaiffie-wp
    ports:
      - "9000:9000"
    volumes:
      - /opt/www:/wordpress
    networks:
      - inception

  ftp:
    build: ./ftp
    container_name: ygaiffier-ftp
    volumes:
      - /opt/www:/opt/www
    ports:
      - "21:21"
    networks:
      - inception
    
networks:
  inception:
    driver: bridge