services:
  webserv:
    build: ./nginx
    container_name: ygaiffie-webserv
    image: ygaiffie-webserv:local
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception

  mariadb:
    build: 
      context: ./mariadb
      dockerfile: dockerfile
      args:
        - MARIADB_DATABASE_ARG=${MARIADB_DATABASE}
        - MARIADB_USER_ARG=${MARIADB_USER}
        - MARIADB_PASSWORD_ARG=${MARIADB_PASSWORD}
    container_name: ygaiffie-db
    image: ygaiffie-mysql:local
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - /home/aska/Inception/vol/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception

  redis:
    build: ./redis
    container_name: ygaiffie-redis
    image: ygaiffie-redis:local
    ports:
      - "6379:6379"
    networks:
      - inception

  wordpress:
    build: ./wp_php
    container_name: ygaiffie-wp
    image: ygaiffie-wordpress:local
    ports:
      - "9000:9000"
    volumes:
      - /home/aska/Inception/vol/wp/:/wordpress
    networks:
      - inception

  ftp:
    build: 
      context: ./ftp
      dockerfile: dockerfile
      args:
        FTP_USER_ARG: ${FTP_USER}
        FTP_USER_PASS_ARG: ${FTP_USER_PASS}
    container_name: ygaiffie-ftp
    image: ygaiffie-ftp:local
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_USER_PASS=${FTP_USER_PASS}
    volumes:
      - /home/aska/Inception/vol/www:/opt/www
    ports:
      - "21:21"
    networks:
      - inception

  adminer:
    build: ./adminer
    container_name: ygaiffie-adminer
    image: ygaiffie-adminer:local
    ports:
      - "8080:8080"
    networks:
      - inception

networks:
  inception:
    driver: bridge