services:
  webserv:
    build: ./nginx
    container_name: ygaiffie-webserv
    image: ygaiffie-webserv:local
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception

  mysql:
    build: ./mariadb
    container_name: ygaiffie-db
    image: ygaiffie-mysql:local
    volumes:
      - /opt/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception

  redis:
    build: ./redis
    container_name: ygaiffie-redis
    image: ygaiffie-redis:local
    ports:
      - "6379:6379"
    networks:
      - inception

  wordpress:
    build: ./wp_php
    container_name: ygaiffie-wp
    image: ygaiffie-wordpress:local
    ports:
      - "9000:9000"
    volumes:
      - ./wp/:/wordpress
    networks:
      - inception

  ftp:
    build: ./ftp
    container_name: ygaiffie-ftp
    image: ygaiffie-ftp:local
    volumes:
      - /opt/www:/opt/www
    ports:
      - "21:21"
    networks:
      - inception

  adminer:
    build: ./adminer
    container_name: ygaiffie-adminer
    image: ygaiffie-adminer:local
    ports:
      - "8080:8080"
    networks:
      - inception

networks:
  inception:
    driver: bridge