services:
  webserv:
    build: ./nginx
    depends_on:
      - wordpress
    container_name: ygaiffie-webserv
    image: ygaiffie-webserv:local
    volumes:
      - ${PROJECT_ROOT}/vol/wp/:/wordpress
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception

  mariadb:
    build: 
      context: ./mariadb
      dockerfile: dockerfile
      args:
        - MARIADB_DATABASE_ARG=${MARIADB_DATABASE}
        - MARIADB_USER_ARG=${MARIADB_USER}
        - MARIADB_PASSWORD_ARG=${MARIADB_PASSWORD}
    container_name: ygaiffie-db
    image: ygaiffie-mysql:local
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ${PROJECT_ROOT}/vol/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception

  redis:
    build: ./redis
    container_name: ygaiffie-redis
    image: ygaiffie-redis:local
    ports:
      - "6379:6379"
    networks:
      - inception

  wordpress:
    build: ./wp_php
    depends_on:
      - mariadb
      - redis
    container_name: ygaiffie-wp
    image: ygaiffie-wordpress:local
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_URL=${WORDPRESS_URL}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
    volumes:
      - ${PROJECT_ROOT}/vol/wp/:/wordpress
    networks:
      - inception

  ftp:
    build: 
      context: ./ftp
      dockerfile: dockerfile
      args:
        FTP_USER_ARG: ${FTP_USER}
        FTP_USER_PASS_ARG: ${FTP_USER_PASS}
    container_name: ygaiffie-ftp
    image: ygaiffie-ftp:local
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_USER_PASS=${FTP_USER_PASS}
    volumes:
      - ${PROJECT_ROOT}/vol/wp:/ftp
    ports:
      - "21:21"
      - "22000-22010:22000-22010"
    networks:
      - inception

  adminer:
    build: ./adminer
    container_name: ygaiffie-adminer
    image: ygaiffie-adminer:local
    ports:
      - "8080:8080"
    networks:
      - inception

networks:
  inception:
    driver: bridge