# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ygaiffie <ygaiffie@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/19 23:21:21 by ygaiffie          #+#    #+#              #
#    Updated: 2024/07/20 18:40:52 by ygaiffie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:3

ARG MARIADB_DATABASE_ARG
ARG MARIADB_USER_ARG
ARG MARIADB_PASSWORD_ARG

ENV MARIADB_DATABASE=${MARIADB_DATABASE_ARG}
ENV MARIADB_USER=${MARIADB_USER_ARG}
ENV MARIADB_PASSWORD=${MARIADB_PASSWORD_ARG}

RUN apk update && apk upgrade
RUN apk add --no-cache mariadb mariadb-client

COPY init.sql /
COPY entrypoint.sh /

RUN mkdir -p /run/mysqld /var/lib/mysql
RUN chown -R mysql:mysql /run/mysqld 
RUN chown -R mysql:mysql /var/lib/mysql

VOLUME /var/lib/mysql

EXPOSE 3306

ENTRYPOINT [ "sh", "entrypoint.sh" ]
