# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ygaiffie <ygaiffie@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/19 23:21:21 by ygaiffie          #+#    #+#              #
#    Updated: 2024/07/20 18:40:52 by ygaiffie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:3

RUN apk update && apk upgrade \
    && apk add --no-cache mariadb mariadb-client bash \
    && mkdir -p /run/mysqld /var/lib/mysql \
    && chown -R mysql:mysql /run/mysqld /var/lib/mysql \
    && sed -i 's/^skip-networking/#skip-networking/' /etc/my.cnf.d/mariadb-server.cnf \
    && rm -rf /tmp/* /var/tmp/* /usr/share/man/* /usr/share/doc/*

COPY entrypoint.sh /

VOLUME /var/lib/mysql
EXPOSE 3306

ENTRYPOINT [ "sh", "entrypoint.sh" ]
