user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    access_log /proc/self/fd/1;
    error_log  /proc/self/fd/2;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        root /opt;
        index index.html;
    }
}