# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ygaiffie <ygaiffie@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/21 05:48:34 by ygaiffie          #+#    #+#              #
#    Updated: 2024/07/21 05:59:40 by ygaiffie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:3

ARG FTP_USER_ARG
ARG FTP_USER_PASS_ARG

ENV FTP_USER=${FTP_USER_ARG}
ENV FTP_USER_PASS=${FTP_USER_PASS_ARG}

RUN apk update && apk add vsftpd
COPY vsftpd.conf /etc/vsftpd.conf
RUN adduser -D -h /ftp/ -s /sbin/nologin ${FTP_USER}
RUN echo "${FTP_USER}:${FTP_USER_PASS}" | chpasswd  
RUN mkdir -p /ftp/
RUN chown ${FTP_USER}:${FTP_USER} /ftp/

EXPOSE 20 21

CMD ["vsftpd", "/etc/vsftpd.conf"]