# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ygaiffie <ygaiffie@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/21 05:48:34 by ygaiffie          #+#    #+#              #
#    Updated: 2024/07/21 05:59:40 by ygaiffie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:3

ARG FTP_USER_ARG
ARG FTP_USER_PASS_ARG

ENV FTP_USER=${FTP_USER_ARG}
ENV FTP_USER_PASS=${FTP_USER_PASS_ARG}

RUN apk update && apk add --no-cache vsftpd && \
    adduser -D -h /ftp/ -s /sbin/nologin "${FTP_USER}" && \
    echo "${FTP_USER}:${FTP_USER_PASS}" | chpasswd && \
    mkdir -p /ftp && \
    chown ${FTP_USER}:${FTP_USER} /ftp && \
    rm -rf /var/tmp/* /usr/share/man/* /usr/share/doc/*

COPY vsftpd.conf /etc/vsftpd.conf

EXPOSE 20 21

CMD ["vsftpd", "/etc/vsftpd.conf"]